action_id: trunk-share-with-everyone
date: 2024-05-29 11:42:19
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1716982939
full_timestamp:
  nanos: 636823000
  seconds: 1716982939
trunk_version: 1.22.1
